.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FREEJ 1 "oct 10, 2007" freej "Digital Instrument for Video Livesets"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
freej \- program to filter video stream
.SH SYNOPSIS
.B freej
.RI [ options ] 
.RI [ files ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B freej
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBfreej\fP is a program that takes a video source and is able to filter it
in various ways.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
.TP
.B \-D\fR\fIlvl\fR
Debug verbosity (default 1).
.TP
.B \-c
Start without console interface.
.TP
.B \-s\fR\fIsize\fR
Size of screen (default 400x300).
.TP
.B \-n
Start with deactivated layers.
.TP
.B \-f <fps> 
set frame per seconds
.TP
.B \-F 
start in fullscreen
.TP
.B \-j <file.js>
execute javascript file


.TP
You can specify any number of files or devices to be loaded as layers.
.TP
The debian version of freej is compiled to support the following layer formats:
.TP
Video4Linux devices as of BTTV cards and webcams
you can specify the size  /dev/video0%160x120
.TP
AVI,ASF,WMA,WMV etc. movies as of codecs supported by your local ffmpeg
This version is dynamically linked!
.TP 
PNG images (also with transparency)
.TP
TXT files rendered with freetype2 library
.TP
SWF flash v.3 layer
.TP
SDL_gfx graphic primitives

.TP
You can assign controllers for interaction:
.br
Keyboard, Midi, Joystick
.TP 
and finally freej can encode everything to ogg/theora and stream it to an icecast server or save it to disc.

.SH SEE ALSO
The javascript API documentation is in 
.IR /usr/share/doc/freej/html,
You find example scripts in
.IR /usr/share/freej
.SH AUTHOR
This manual page was written by Guido Trotter <ultrotter@quaqua.net>,
for the Debian GNU/Linux system (but may be used by others).
Some additions from MrGoil
