# type make and this makefile will generate the html documentation

all:
	./jsdoc.pl -d html --project-name "<a href="http://freej.dyne.org">FreeJ</a> scripting" --logo "ipernav-small.png" --page-footer "`cat footer.html`" FreejScripting.js

clean:
	rm -rf html
